const footNotesDic: Record<string, string> = {
  "yv": "K<sup>+</sup> salt and adjusted to protonation constant.",
  "yz": "Tetraalkyl ammonium salt and adjusted to protonation constant.",
  "ta": "Temperature range not stated.",
  "tb": "Temperature range = 0-20 ░C.",
  "tc": "Temperature range = 0-30 ░C.",
  "td": "Temperature range = 0-40 ░C.",
  "te": "Temperature range = 0-50 ░C.",
  "tf": "Temperature range = 0-60 ░C.",
  "tg": "Temperature range = 0-70 ░C.",
  "th": "Temperature range = 0-80 ░C.",
  "ti": "Temperature range = 0-90 ░C.",
  "tj": "Temperature range = 0-100 ░C.",
  "tk": "Temperature range = 10-20 ░C.",
  "tl": "Temperature range = 10-30 ░C.",
  "tm": "Temperature range = 10-40 ░C.",
  "tn": "Temperature range = 10-50 ░C.",
  "to": "Temperature range = 10-60 ░C.",
  "tp": "Temperature range = 10-70 ░C.",
  "tq": "Temperature range = 10-90 ░C.",
  "tr": "Temperature range = 20-100 ░C.",
  "ts": "Temperature range = 20-30 ░C.",
  "tu": "Temperature range = 20-40 ░C.",
  "tw": "Temperature range = 20-50 ░C.",
  "tx": "Temperature range = 20-60 ░C.",
  "ty": "Temperature range = 20-70 ░C.",
  "tz": "Temperature range = 20-80 ░C.",
  "ua": "Temperature range = 20-300 ░C.",
  "ub": "Temperature range = 30-40 ░C.",
  "uc": "Temperature range = 30-50 ░C.",
  "ud": "Temperature range = 30-60 ░C.",
  "ue": "Temperature range = 60-150 ░C.",
  "uf": "0-40 and NaClO<sub>4</sub> used as background electrolyte.",
  "ug": "10-60 and Na<sup>+</sup> salt used as background electrolyte.",
  "uh": "10-40 and Na<sup>+</sup> salt used as background electrolyte.",
  "ui": "10-40 and K<sup>+</sup> salt used as background electrolyte.",
  "uj": "0-40 and optical isomerism not stated.",
  "uk": "10-40 and optical isomerism not stated.",
  "ul": "20-50 and DL-mixture.",
  "um": "0-40 and tetraalkyl ammonium salt used as background electrolyte.",
  "a": "L-, D-, and DL-isomers had same values.",
  "aa": "NaClO<sub>4</sub> used as background electrolyte.",
  "ab": "Intermediate complex and (CH<sub>3</sub>)<sub>4</sub>NCl background electrolyte.",
  "ac": "KClO<sub>4</sub> used as background electrolyte.",
  "b": "Optical isomerism not stated.",
  "bb": "NaCl used as background electrolyte.",
  "bc": "NaBr used as background electrolyte.",
  "bd": "NaI used as background electrolyte.",
  "c": "DL-mixture.",
  "cc": "NaNO<sub>3</sub> used as background electrolyte.",
  "d": "DL-, allo- mixture.",
  "dd": "KCl used as background electrolyte.",
  "e": "Cis isomer.",
  "ee": "LiClO<sub>4</sub> used as background electrolyte.",
  "f": "Trans isomer.",
  "ff": "Corrected for large excess of ligand.",
  "g": "Not corrected for chloride ion.",
  "gg": "KBr used as background electrolyte.",
  "h": "D-isomer.",
  "hh": "KNO<sub>3</sub> used as background electrolyte.",
  "ii": "NH<sub>4</sub>NO<sub>3</sub> used as background electrolyte.",
  "ij": "Ligand NO<sub>3</sub> used as background electrolyte.",
  "ik": "Ligand ClO<sub>4</sub> used as background electrolyte.",
  "j": "Corrected for background electrolyte.",
  "jj": "NH<sub>4</sub>Cl used as background electrolyte.",
  "k": "Molal.",
  "ka": "Molal and NaClO<sub>4</sub> used as background electrolyte.",
  "kb": "Molal and NaCl used as background electrolyte.",
  "ki": "Molal and NH<sub>4</sub>NO<sub>3</sub> used as background electrolyte.",
  "m": "Acetate buffer.",
  "mm": "HClO<sub>4</sub> used as background electrolyte.",
  "n": "Assuming [HL]/[H][L] = 13.87.",
  "nn": "HCl used as background electrolyte.",
  "o": "Assuming [HL]/[H][L] = 14.6 and NaClO<sub>4</sub> used as background electrolyte.",
  "oo": "LiCl used as background electrolyte.",
  "p": "Value adjusted for compatibility with other values.",
  "pa": "NaClO<sub>4</sub> salt and adjusted for compatibility with other values.",
  "ph": "D-isomer and value adjusted for compatibility with other values.",
  "pp": "NH<sub>4</sub>ClO<sub>4</sub> used as background electrolyte.",
  "q": "AgNO<sub>3</sub> used as background electrolyte.",
  "qq": "HNO<sub>3</sub> used as background electrolyte.",
  "r": "Assuming [HL]/[H][L] = 0.83 and HClO<sub>4</sub> used as background electrolyte.",
  "rr": "Solid = hydrocerussite.",
  "s": "In synthetic seawater.",
  "sp": "Solid = sepiolite.",
  "ss": "Solid = plumbonacrite.",
  "u": "Na<sup>+</sup> salt used as background electrolyte.",
  "v": "K<sup>+</sup> salt used as background electrolyte.",
  "w": "NH<sub>4</sub><sup>+</sup> salt used as background electrolyte.",
  "x": "Li<sup>+</sup> salt used as background electrolyte.",
  "y": "Value adjusted to be compatible with listed protonation constants.",
  "ya": "Value adjusted to be compatible with listed protonation enthalpy.",
  "z": "Tetraalkyl ammonium salt used as background electrolyte.",
  "za": "Tetramethyl ammonium salt used as background electrolyte.",
  "zb": "Tetraethyl ammonium salt used as background electrolyte.",
  "zc": "Tetrapropyl ammonium salt used as background electrolyte.",
  "pd": "Me<sub>4</sub>N<sup>+</sup> salt and adjusted for compatiblity with other values.",
  "pe": "Et<sub>4</sub>N<sup>+</sup> salt and adjusted for compatiblity with other values.",
  "zf": "Pr<sub>4</sub>N<sup>+</sup> salt and adjusted for compatiblity with other values.",
  "pu": "Na<sup>+</sup> salt and adjusted for compatiblity with other values.",
  "pv": "K<sup>+</sup> salt and adjusted for compatiblity with other values.",
  "pz": "R<sub>4</sub>N<sup>+</sup> salt and adjusted for compatiblity with other values.",
  "yu": "Na<sup>+</sup> salt and adjusted to protonation constant.",
  "un": "10-40 and K<sup>+</sup> salt used as background electrolyte.",
  "uo": "10-40 and tetraalkyl ammonium salt used as background electrolyte.",
  "up": "10-50 and tetraalkyl ammonium salt used as background electrolyte.",
  "uq": "20-40 and NaClO<sub>4</sub> used as background electrolyte.",
  "ur": "20-40 and K<sup>+</sup> salt used as background electrolyte.",
  "us": "10-50 and Na<sup>+</sup> salt used as background electrolyte.",
  "ut": "30-50 and optical isomerism not stated.",
  "uv": "20-40 and tetraalkyl ammonium salt used as background electrolyte.",
  "uw": "20-70 and NH<sub>4</sub><sup>+</sup> salt used as background electrolyte.",
  "ux": "10-50 and K<sup>+</sup> salt used as background electrolyte.",
  "uy": "20-30 and NaClO<sub>4</sub> used as background electrolyte.",
  "uz": "10-40 and NaClO<sub>4</sub> used as background electrolyte.",
  "va": "20-40 and NaClO<sub>4</sub> used as background electrolyte.",
  "vb": "10-40 and value adjusted for compatibility with other values.",
  "vc": "20-40 and NaNO<sub>3</sub> used as background electrolyte.",
  "vd": "20-50 and NaClO<sub>4</sub> used as background electrolyte.",
  "ve": "0-60 and molal.",
  "vf": "10-30 and assuming [HL]/[H][L] = 13.87.",
  "vg": "0-100 and molal.",
  "vh": "20-100 and NaClO<sub>4</sub> used as background electrolyte.",
  "vi": "60-150 and molal.",
  "vj": "10-60 and NaClO<sub>4</sub> used as background electrolyte.",
  "vk": "10-40 and NH<sub>4</sub>NO<sub>3</sub> used as background electrolyte.",
  "vl": "10-60 and NH<sub>4</sub>NO<sub>3</sub> used as background electrolyte.",
  "vm": "20-50 and tetraalkyl ammonium salt used as background electrolyte.",
  "vn": "0-70 and Na<sup>+</sup> salt used as background electrolyte.",
  "vo": "0-30 and HClO<sub>4</sub> used as background electrolyte.",
  "vp": "10-40 and HCl used as background electrolyte.",
  "vq": "10-60 and LiClO<sub>4</sub> used as background electrolyte.",
  "vr": "0-70 and LiClO<sub>4</sub> used as background electrolyte.",
  "vs": "10-40 and molal.",
  "vt": "0-50 and NaClO<sub>4</sub> used as background electrolyte.",
  "kk": "The non-critical data may be found in the reference."
}

export default class FootNoteUtils {
  public static fromLegacyId(id: string) {
    return footNotesDic[id]
  }
}
